language: node_js

node_js: – 16.0.0

script: cd docs && vercel --prod

before_script: echo before script
after_script:
  - echo after script
  - echo yeah! success!

cache:
  directories: – node_modules
