language: node_js

node_js: – 16.0.0

script: cd docs && vercel --prod

before_script:
  - echo before script
  - npm i -g vercel
  - vercel --prod --token $TRAVIS_CI

after_script:
  - echo after script
  - echo yeah! success!

cache:
  directories: – node_modules
